# Generated by Django 5.0 on 2025-12-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='days_allowed',
            field=models.IntegerField(default=21),
        ),
    ]
