# Generated by Django 5.0 on 2025-12-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_model',
            field=models.CharField(max_length=50),
        ),
    ]
