# Generated by Django 5.0 on 2025-12-30 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employeeprofile_department_and_more'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancereview',
            name='cycle',
        ),
        migrations.AddField(
            model_name='performancereview',
            name='review_period',
            field=models.CharField(default='Q4 2025', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='core.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='PerformanceGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employeeprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='PerformanceCycle',
        ),
    ]
