# Generated by Django 5.0 on 2026-01-02 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_remove_employeeprofile_department_and_more'),
        ('performance', '0002_remove_performancereview_cycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancereview',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='review_period',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='performancereview',
            name='review_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('progress', models.IntegerField(default=0)),
                ('assigned_to', models.ManyToManyField(to='core.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='PerformanceGoal',
        ),
    ]
