# Generated by Django 5.0 on 2026-01-05 12:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee_user'),
        ('performance', '0003_remove_performancereview_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancereview',
            name='review_date',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='score',
        ),
        migrations.AddField(
            model_name='performancereview',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancereview',
            name='goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancereview',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='title',
            field=models.CharField(default='Initial Review', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.employee'),
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
