# Generated by Django 5.0 on 2025-12-30 01:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employeeprofile_department_and_more'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='period',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='earnings_breakdown',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='generated_at',
        ),
        migrations.AddField(
            model_name='payslip',
            name='month',
            field=models.CharField(default='January', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='payment_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_allowances',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='year',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.employeeprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='PayrollPeriod',
        ),
    ]
