# Generated by Django 5.0 on 2026-01-02 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_remove_salarystructure_employee_payrollrecord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollrecord',
            old_name='salary',
            new_name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='month',
            field=models.CharField(default='January 2026', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='pay_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='tax_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
