# Generated by Django 5.0 on 2026-01-02 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_remove_employeeprofile_department_and_more'),
        ('payroll', '0002_remove_payslip_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarystructure',
            name='employee',
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Payslip',
        ),
        migrations.DeleteModel(
            name='SalaryStructure',
        ),
    ]
