# Generated by Django 5.0 on 2026-01-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_remove_employeeprofile_department_and_more'),
        ('leave', '0003_remove_leavetype_organization_and_more'),
        ('payroll', '0003_remove_salarystructure_employee_payrollrecord_and_more'),
        ('performance', '0003_remove_performancereview_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
        migrations.DeleteModel(
            name='OrganizationTenant',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
